/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pizzk.gradle.plugin

import org.gradle.api.Plugin
import org.gradle.api.Project
import pizzk.gradle.plugin.support.MavenInject

/**
 * 'maven repo' plugin.
 */
class MavenRepoPlugin : Plugin<Project> {
    companion object {
        const val NAME = "mavenrepo"
    }

    override fun apply(project: Project) {
        MavenRepoApi(project).extend()
        MavenRepoTask(project).setup()
        project.afterEvaluate(MavenInject()::apply)
    }
}
