/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pizzk.gradle.plugin

import org.gradle.api.Plugin
import org.gradle.api.Project
import pizzk.gradle.plugin.index.MavenRepoApi
import pizzk.gradle.plugin.index.MavenRepoInject
import pizzk.gradle.plugin.index.MavenRepoTask

interface PluginComponent : Plugin<Project>

/**
 * 'maven repo' plugin.
 */
class MavenRepoPlugin : Plugin<Project> {
    companion object {
        const val NAME = "mavenrepo"
    }

    override fun apply(project: Project) {
        MavenRepoApi.apply(project)
        MavenRepoTask.apply(project)
        MavenRepoInject.apply(project)
    }
}
