/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pizzk.gradle.plugin

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * 'maven repo' plugin.
 */
class MavenRepoPlugin : Plugin<Project> {
    companion object {
        const val NAME = "mavenrepo"
    }

    override fun apply(project: Project) {
        project.extensions.add(MavenRepoApi.NAME, MavenRepoApi(project))
        MavenRepoTask(project).setup()
    }
}
